services:
  server:
    image: golang:1.23
    restart: unless-stopped
    depends_on:
      - nats-streaming
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go

  nats-streaming:
    image: nats-streaming:0.11.2
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"